var h;h||=typeof Module != 'undefined' ? Module : {};var aa=[],ba="./this.program",ca=globalThis.document?.currentScript?.src,da="",ea;try{da=(new URL(".",ca)).href}catch{}ea=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);};var fa=console.log.bind(console),k=console.error.bind(console),l=!1,ha;function ia(){var a=h.preRun;a&&(typeof a=="function"&&(a=[a]),ja.push(...a));for(a=ja;a.length>0;)a.shift()(h)}
function ka(){var a=h.postRun;a&&(typeof a=="function"&&(a=[a]),la.push(...a));for(a=la;a.length>0;)a.shift()(h)}function n(a){h.onAbort?.(a);a=`Aborted(${a})`;k(a);l=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ma;async function na(a){try{var b=await ea(a);return new Uint8Array(b)}catch{}throw"both async and sync fetching of the wasm failed";}
async function oa(a,b){try{var c=await na(a);return await WebAssembly.instantiate(c,b)}catch(d){k(`failed to asynchronously prepare wasm: ${d}`),n(d)}}async function pa(a){var b=ma;try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){k(`wasm streaming compile failed: ${d}`),k("falling back to ArrayBuffer instantiation")}return oa(b,a)}class qa{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var ra,q,sa,r,u,x,ta,y,z,la=[],ja=[],ua=!0,va=new TextDecoder,wa=(a,b,c)=>{for(c=b+c;a[b]&&!(b>=c);)++b;return b},A=(a,b)=>a?va.decode(z.subarray(a,wa(z,a,b))):"",xa=0,ya={},za=a=>{if(!(a instanceof qa||a=="unwind"))throw a;},Aa=a=>{ha=a;ua||xa>0||(h.onExit?.(a),l=!0);throw new qa(a);},Ba=()=>{if(!(ua||xa>0))try{var a=ha;ha=a;Aa(a)}catch(b){za(b)}},Ca=a=>{if(!l)try{return a()}catch(b){za(b)}finally{Ba()}},Da=[],Ea=(a,b)=>{Da.length=0;for(var c;c=z[a++];){var d=c!=105;d&=c!=112;b+=d&&b%8?4:0;Da.push(c==
112?y[b>>2]:c==106?sa[b>>3]:c==105?q[b>>2]:x[b>>3]);b+=d?8:4}return Da},Fa=[0,document,window],C=a=>{a=a>2?A(a):a;return Fa[a]||document.querySelector(a)},Ga=a=>Fa.indexOf(a)<0?a.getBoundingClientRect():{left:0,top:0};function Ha(a){var b=D.cf[a];b.target.removeEventListener(b.ef,b.mg,b.lf);D.cf.splice(a,1)}function Ia(){if(navigator.userActivation?navigator.userActivation.isActive:D.ag&&D.Bg.Sf){var a=D.pf;D.pf=[];for(var b of a)b.eg(...b.lg)}}
function E(a){if(!a.target)return-4;if(a.hf)a.mg=function(c){++D.ag;D.Bg=a;Ia();a.qf(c);Ia();--D.ag},a.target.addEventListener(a.ef,a.mg,a.lf),D.cf.push(a);else for(var b=0;b<D.cf.length;++b)D.cf[b].target==a.target&&D.cf[b].ef==a.ef&&Ha(b--);return 0}function Ja(a){return a==window?"#window":a==screen?"#screen":a?.nodeName??""}
var D={Og:0,Zf:0,Wg:0,Kf:0,ih:0,gg:0,Vf:0,Tg:0,Yg:0,Sg:0,Yf:0,bg:0,jg:0,fg:0,$g(){for(;D.cf.length;)Ha(D.cf.length-1);D.pf=[]},ag:0,pf:[],Rg(a,b,c){function d(f,g){if(f.length!=g.length)return!1;for(var m in f)if(f[m]!=g[m])return!1;return!0}for(var e of D.pf)if(e.eg==a&&d(e.lg,c))return;D.pf.push({eg:a,rg:b,lg:c});D.pf.sort((f,g)=>f.rg-g.rg)},bh(a){D.pf=D.pf.filter(b=>b.eg!=a)},cf:[],ah:(a,b)=>{for(var c=0;c<D.cf.length;++c)D.cf[c].target!=a||b&&b!=D.cf[c].ef||Ha(c--)},dh(a){var b=!1;for(let c=0;c<
D.cf.length;++c){let d=D.cf[c];d.target===a.target&&d.kf===a.kf&&d.hf===a.hf&&d.mf===a.mf&&(Ha(c--),b=!0)}return b?0:-5},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},F=(a,b,c)=>{var d=z;if(!(c>0))return 0;var e=b;c=b+c-1;for(var f=0;f<a.length;++f){var g=a.codePointAt(f);if(g<=127){if(b>=c)break;d[b++]=g}else if(g<=2047){if(b+1>=c)break;d[b++]=192|g>>6;d[b++]=128|g&63}else if(g<=65535){if(b+2>=c)break;d[b++]=224|g>>12;d[b++]=128|g>>6&63;d[b++]=128|g&63}else{if(b+
3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63;d[b++]=128|g>>6&63;d[b++]=128|g&63;f++}}d[b]=0;return b-e},Ka=(a,b)=>{x[a>>3]=b.timestamp;for(var c=0;c<b.axes.length;++c)x[a+c*8+16>>3]=b.axes[c];for(c=0;c<b.buttons.length;++c)x[a+c*8+528>>3]=typeof b.buttons[c]=="object"?b.buttons[c].value:b.buttons[c];for(c=0;c<b.buttons.length;++c)r[a+c+1040]=typeof b.buttons[c]=="object"?b.buttons[c].pressed:b.buttons[c]==1;r[a+1104]=b.connected;q[a+1108>>2]=b.index;q[a+8>>2]=b.axes.length;q[a+12>>2]=b.buttons.length;
F(b.id,a+1112,64);F(b.mapping,a+1176,64)},G,La=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,f)=>b.drawArraysInstancedANGLE(c,d,e,f),a.drawElementsInstanced=(c,d,e,f,g)=>b.drawElementsInstancedANGLE(c,d,e,f,g))},Ma=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),
a.isVertexArray=c=>b.isVertexArrayOES(c))},Na=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},Oa=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return a.getSupportedExtensions()?.filter(c=>b.includes(c))??[]},Pa=1,Qa=[],H=[],Ra=[],Sa=[],Ta=[],I=[],Ua=[],Va=[],J=[],Wa={},Xa=4,Ya=0,Za=a=>{for(var b=Pa++,c=a.length;c<b;c++)a[c]=null;return b},$a=(a,b,c,d)=>{for(var e=0;e<a;e++){var f=G[c](),g=f&&Za(d);f?(f.name=g,d[g]=f):K||=1282;q[b+e*4>>2]=g}},bb=(a,b)=>{a.Ze||(a.Ze=a.getContext,a.getContext=function(d,e){e=a.Ze(d,e);return d=="webgl"==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?ab(c,b):0},ab=(a,b)=>
{var c=Za(Va),d={handle:c,attributes:b,version:b.Gg,Rf:a};a.canvas&&(a.canvas.Lg=d);Va[c]=d;if(typeof b.Cg=="undefined"||b.Cg)if((a=d)||(a=cb),!a.Fg){a.Fg=!0;a=a.Rf;a.Xg=a.getExtension("WEBGL_multi_draw");a.Eg=a.getExtension("EXT_polygon_offset_clamp");a.Dg=a.getExtension("EXT_clip_control");a.Kg=a.getExtension("WEBGL_polygon_mode");La(a);Ma(a);Na(a);a.jf=a.getExtension("EXT_disjoint_timer_query");for(var e of Oa(a))e.includes("lose_context")||e.includes("debug")||a.getExtension(e)}return c},db={},
K,cb,eb=a=>G.activeTexture(a),fb=(a,b)=>{G.attachShader(H[a],I[b])},gb=(a,b,c)=>{G.bindAttribLocation(H[a],b,A(c))},hb=(a,b)=>{G.bindBuffer(a,Qa[b])},ib=(a,b)=>{G.bindFramebuffer(a,Ra[b])},jb=(a,b)=>{G.bindRenderbuffer(a,Sa[b])},kb=(a,b)=>{G.bindTexture(a,Ta[b])},lb=a=>G.blendEquation(a),mb=(a,b)=>G.blendEquationSeparate(a,b),nb=(a,b)=>G.blendFunc(a,b),ob=(a,b,c,d)=>G.blendFuncSeparate(a,b,c,d),pb=(a,b,c,d)=>{G.bufferData(a,c?z.subarray(c,c+b):b,d)},qb=(a,b,c,d)=>{G.bufferSubData(a,b,z.subarray(d,
d+c))},rb=a=>G.checkFramebufferStatus(a),sb=a=>G.clear(a),tb=(a,b,c,d)=>G.clearColor(a,b,c,d),ub=a=>G.clearDepth(a),vb=a=>{G.compileShader(I[a])},wb=(a,b,c,d,e,f,g,m)=>{G.compressedTexImage2D(a,b,c,d,e,f,z.subarray(m,m+g))},xb=()=>{var a=Za(H),b=G.createProgram();b.name=a;b.If=b.Gf=b.Hf=0;b.hg=1;H[a]=b;return a},yb=a=>{var b=Za(I);I[b]=G.createShader(a);return b},zb=a=>G.cullFace(a),Ab=(a,b)=>{for(var c=0;c<a;c++){var d=q[b+c*4>>2],e=Qa[d];e&&(G.deleteBuffer(e),e.name=0,Qa[d]=null)}},Bb=a=>{if(a){var b=
H[a];b?(G.deleteProgram(b),b.name=0,H[a]=null):K||=1281}},Cb=a=>{if(a){var b=I[a];b?(G.deleteShader(b),I[a]=null):K||=1281}},Db=(a,b)=>{for(var c=0;c<a;c++){var d=q[b+c*4>>2],e=Ta[d];e&&(G.deleteTexture(e),e.name=0,Ta[d]=null)}},Eb=a=>G.depthFunc(a),Fb=(a,b)=>{G.detachShader(H[a],I[b])},Gb=a=>G.disable(a),Hb=a=>{G.disableVertexAttribArray(a)},Ib=(a,b,c)=>{G.drawArrays(a,b,c)},Jb=[],Kb=(a,b,c,d)=>{G.drawElements(a,b,c,d)},Lb=a=>G.enable(a),Mb=a=>{G.enableVertexAttribArray(a)},Nb=(a,b,c,d)=>{G.framebufferRenderbuffer(a,
b,c,Sa[d])},Ob=(a,b,c,d,e)=>{G.framebufferTexture2D(a,b,c,Ta[d],e)},Pb=a=>G.frontFace(a),Qb=(a,b)=>{$a(a,b,"createBuffer",Qa)},Rb=(a,b)=>{$a(a,b,"createFramebuffer",Ra)},Sb=(a,b)=>{$a(a,b,"createRenderbuffer",Sa)},Tb=(a,b)=>{$a(a,b,"createTexture",Ta)},Ub=(a,b,c,d,e,f,g,m)=>{b=H[b];if(a=G[a](b,c))d=m&&F(a.name,m,d),e&&(q[e>>2]=d),f&&(q[f>>2]=a.size),g&&(q[g>>2]=a.type)},Vb=(a,b)=>G.getAttribLocation(H[a],A(b)),Wb=(a,b,c)=>{if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:c!=0&&c!=1&&(K||=
1280);return;case 36345:d=0;break;case 34466:var e=G.getParameter(34467);d=e?e.length:0}if(d===void 0)switch(e=G.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":K||=1280;return;case "object":if(e===null)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;default:K||=1280;return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:q[b+
a*4>>2]=e[a];break;case 2:u[b+a*4>>2]=e[a];break;case 4:r[b+a]=e[a]?1:0}return}try{d=e.name|0}catch(f){K||=1280;k(`GL_INVALID_ENUM in glGet${c}v: Unknown object returned from WebGL getParameter(${a})! (error: ${f})`);return}}break;default:K||=1280;k(`GL_INVALID_ENUM in glGet${c}v: Native code calling glGet${c}v(${a}) and it returns ${e} of type ${typeof e}!`);return}switch(c){case 1:c=d;y[b>>2]=c;y[b+4>>2]=(c-y[b>>2])/4294967296;break;case 0:q[b>>2]=d;break;case 2:u[b>>2]=d;break;case 4:r[b]=d?1:
0}}else K||=1281},Xb=(a,b)=>Wb(a,b,2),Yb=(a,b,c,d)=>{a=G.getProgramInfoLog(H[a]);a===null&&(a="(unknown error)");b=b>0&&d?F(a,d,b):0;c&&(q[c>>2]=b)},Zb=(a,b,c)=>{if(c)if(a>=Pa)K||=1281;else if(a=H[a],b==35716)a=G.getProgramInfoLog(a),a===null&&(a="(unknown error)"),q[c>>2]=a.length+1;else if(b==35719){if(!a.If){var d=G.getProgramParameter(a,35718);for(b=0;b<d;++b)a.If=Math.max(a.If,G.getActiveUniform(a,b).name.length+1)}q[c>>2]=a.If}else if(b==35722){if(!a.Gf)for(d=G.getProgramParameter(a,35721),
b=0;b<d;++b)a.Gf=Math.max(a.Gf,G.getActiveAttrib(a,b).name.length+1);q[c>>2]=a.Gf}else if(b==35381){if(!a.Hf)for(d=G.getProgramParameter(a,35382),b=0;b<d;++b)a.Hf=Math.max(a.Hf,G.getActiveUniformBlockName(a,b).length+1);q[c>>2]=a.Hf}else q[c>>2]=G.getProgramParameter(a,b);else K||=1281},$b=(a,b,c)=>{if(c){a=G.jf.getQueryObjectEXT(J[a],b);var d;typeof a=="boolean"?d=a?1:0:d=a;y[c>>2]=d;y[c+4>>2]=(d-y[c>>2])/4294967296}else K||=1281},ac=(a,b,c)=>{if(c){a=G.jf.getQueryObjectEXT(J[a],b);var d;typeof a==
"boolean"?d=a?1:0:d=a;q[c>>2]=d}else K||=1281},bc=(a,b,c,d)=>{a=G.getShaderInfoLog(I[a]);a===null&&(a="(unknown error)");b=b>0&&d?F(a,d,b):0;c&&(q[c>>2]=b)},cc=(a,b,c)=>{c?b==35716?(a=G.getShaderInfoLog(I[a]),a===null&&(a="(unknown error)"),q[c>>2]=a?a.length+1:0):b==35720?(a=G.getShaderSource(I[a]),q[c>>2]=a?a.length+1:0):q[c>>2]=G.getShaderParameter(I[a],b):K||=1281},dc=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);d<=127?b++:d<=2047?b+=2:d>=55296&&d<=57343?(b+=4,++c):b+=3}return b},
ec=a=>{var b=dc(a)+1,c=L(b);c&&F(a,c,b);return c},fc=()=>{var a=Oa(G);return a=a.concat(a.map(b=>"GL_"+b))},hc=a=>{var b=Wa[a];if(!b){switch(a){case 7939:b=ec(fc().join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=G.getParameter(a))||(K||=1280);b=b?ec(b):0;break;case 7938:b=ec(`OpenGL ES 2.0 (${G.getParameter(7938)})`);break;case 35724:b=G.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);c!==null&&(c[1].length==3&&(c[1]+="0"),b=`OpenGL ES GLSL ES ${c[1]} (${b})`);
b=ec(b);break;default:K||=1280}Wa[a]=b}return b},ic=a=>a.slice(-1)=="]"&&a.lastIndexOf("["),jc=a=>{var b=a.vf,c=a.wg,d;if(!b){a.vf=b={};a.vg={};var e=G.getProgramParameter(a,35718);for(d=0;d<e;++d){var f=G.getActiveUniform(a,d);var g=f.name;f=f.size;var m=ic(g);m=m>0?g.slice(0,m):g;var p=a.hg;a.hg+=f;c[m]=[f,p];for(g=0;g<f;++g)b[p]=g,a.vg[p++]=m}}},kc=(a,b)=>{b=A(b);if(a=H[a]){jc(a);var c=a.vf,d=0,e=b,f=ic(b);f>0&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.wg[e])&&d<e[0]&&(d+=e[1],c[d]=
c[d]||G.getUniformLocation(a,b)))return d}else K||=1281;return-1},M=(a,b)=>{if(a){var c=a.vf[b];typeof c=="number"&&(a.vf[b]=c=G.getUniformLocation(a,a.vg[b]+(c>0?`[${c}]`:"")));return c}K||=1282},lc=(a,b,c,d)=>{if(c)if(a=H[a],jc(a),a=G.getUniform(a,M(a,b)),typeof a=="number"||typeof a=="boolean")switch(d){case 0:q[c>>2]=a;break;case 2:u[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:q[c+b*4>>2]=a[b];break;case 2:u[c+b*4>>2]=a[b]}else K||=1281},mc=(a,b,c,d)=>{if(c)if(a=G.getVertexAttrib(a,b),
b==34975)q[c>>2]=a&&a.name;else if(typeof a=="number"||typeof a=="boolean")switch(d){case 0:q[c>>2]=a;break;case 2:u[c>>2]=a;break;case 5:q[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:q[c+b*4>>2]=a[b];break;case 2:u[c+b*4>>2]=a[b];break;case 5:q[c+b*4>>2]=Math.fround(a[b])}else K||=1281},nc=a=>{a=H[a];G.linkProgram(a);a.vf=0;a.wg={}},oc=(a,b)=>{a==3317?Xa=b:a==3314&&(Ya=b);G.pixelStorei(a,b)},pc=(a,b,c,d,e)=>{a-=5120;a=a==1?z:a==4?q:a==6?u:a==5||a==28922?y:ta;b=d*(({5:3,6:4,
8:2,29502:3,29504:4}[b-6402]||1)*a.BYTES_PER_ELEMENT*(Ya||c)+Xa-1&-Xa);return a.subarray(e>>>31-Math.clz32(a.BYTES_PER_ELEMENT),e+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},qc=(a,b,c,d,e,f,g)=>{(g=pc(f,e,c,d,g))?G.readPixels(a,b,c,d,e,f,g):K||=1280},rc=(a,b,c,d)=>G.renderbufferStorage(a,b,c,d),sc=(a,b,c,d)=>G.scissor(a,b,c,d),tc=(a,b,c,d)=>{for(var e="",f=0;f<b;++f)e+=A(y[c+f*4>>2],d?y[d+f*4>>2]:void 0);G.shaderSource(I[a],e)},uc=(a,b,c,d,e,f,g,m,p)=>{p=p?pc(m,g,d,e,p):null;G.texImage2D(a,b,c,d,e,f,
g,m,p)},vc=(a,b,c)=>G.texParameteri(a,b,c),N=[],wc=(a,b,c)=>{if(b<=288)for(var d=N[b],e=0;e<b;++e)d[e]=u[c+4*e>>2];else d=u.subarray(c>>2,c+b*4>>2);G.uniform1fv(M(G.af,a),d)},xc=(a,b)=>{G.uniform1i(M(G.af,a),b)},yc=[],zc=(a,b,c)=>{if(b<=288)for(var d=yc[b],e=0;e<b;++e)d[e]=q[c+4*e>>2];else d=q.subarray(c>>2,c+b*4>>2);G.uniform1iv(M(G.af,a),d)},Ac=(a,b,c)=>{if(b<=144){b*=2;for(var d=N[b],e=0;e<b;e+=2)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2]}else d=u.subarray(c>>2,c+b*8>>2);G.uniform2fv(M(G.af,a),d)},
Bc=(a,b,c)=>{if(b<=144){b*=2;for(var d=yc[b],e=0;e<b;e+=2)d[e]=q[c+4*e>>2],d[e+1]=q[c+(4*e+4)>>2]}else d=q.subarray(c>>2,c+b*8>>2);G.uniform2iv(M(G.af,a),d)},Cc=(a,b,c)=>{if(b<=96){b*=3;for(var d=N[b],e=0;e<b;e+=3)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2]}else d=u.subarray(c>>2,c+b*12>>2);G.uniform3fv(M(G.af,a),d)},Dc=(a,b,c)=>{if(b<=96){b*=3;for(var d=yc[b],e=0;e<b;e+=3)d[e]=q[c+4*e>>2],d[e+1]=q[c+(4*e+4)>>2],d[e+2]=q[c+(4*e+8)>>2]}else d=q.subarray(c>>2,c+b*12>>2);G.uniform3iv(M(G.af,
a),d)},Ec=(a,b,c,d,e)=>{G.uniform4f(M(G.af,a),b,c,d,e)},Fc=(a,b,c)=>{if(b<=72){var d=N[4*b],e=u;c>>=2;b*=4;for(var f=0;f<b;f+=4){var g=c+f;d[f]=e[g];d[f+1]=e[g+1];d[f+2]=e[g+2];d[f+3]=e[g+3]}}else d=u.subarray(c>>2,c+b*16>>2);G.uniform4fv(M(G.af,a),d)},Gc=(a,b,c)=>{if(b<=72){b*=4;for(var d=yc[b],e=0;e<b;e+=4)d[e]=q[c+4*e>>2],d[e+1]=q[c+(4*e+4)>>2],d[e+2]=q[c+(4*e+8)>>2],d[e+3]=q[c+(4*e+12)>>2]}else d=q.subarray(c>>2,c+b*16>>2);G.uniform4iv(M(G.af,a),d)},Hc=(a,b,c,d)=>{if(b<=18){var e=N[16*b],f=u;
d>>=2;b*=16;for(var g=0;g<b;g+=16){var m=d+g;e[g]=f[m];e[g+1]=f[m+1];e[g+2]=f[m+2];e[g+3]=f[m+3];e[g+4]=f[m+4];e[g+5]=f[m+5];e[g+6]=f[m+6];e[g+7]=f[m+7];e[g+8]=f[m+8];e[g+9]=f[m+9];e[g+10]=f[m+10];e[g+11]=f[m+11];e[g+12]=f[m+12];e[g+13]=f[m+13];e[g+14]=f[m+14];e[g+15]=f[m+15]}}else e=u.subarray(d>>2,d+b*64>>2);G.uniformMatrix4fv(M(G.af,a),!!c,e)},Ic=a=>{a=H[a];G.useProgram(a);G.af=a},Jc=(a,b,c,d,e,f)=>{G.vertexAttribPointer(a,b,c,!!d,e,f)},Kc=(a,b,c,d)=>G.viewport(a,b,c,d),Lc=()=>{try{if(navigator.getGamepads)return(D.Ff=
navigator.getGamepads())?0:-1}catch(a){navigator.getGamepads=null}return-1},Mc=(a,b,c,d,e,f)=>{D.Vf||(D.Vf=L(256));a={target:C(a),ef:f,kf:e,mf:b,hf:d,qf:g=>{var m=g.target.id??"",p=D.Vf;F(Ja(g.target),p+0,128);F(m,p+128,128);O(d,e,p,b)&&g.preventDefault()},lf:c};return E(a)},Nc=(a,b,c,d,e,f)=>{D.Kf||(D.Kf=L(64));a=C(a);return E({target:a,Sf:f!="mousemove"&&f!="mouseenter"&&f!="mouseleave",ef:f,kf:e,mf:b,hf:d,qf:g=>{var m=a,p=D.Kf;x[p>>3]=g.timeStamp;var t=p>>2;q[t+2]=g.screenX;q[t+3]=g.screenY;q[t+
4]=g.clientX;q[t+5]=g.clientY;r[p+24]=g.ctrlKey;r[p+25]=g.shiftKey;r[p+26]=g.altKey;r[p+27]=g.metaKey;ra[t*2+14]=g.button;ra[t*2+15]=g.buttons;q[t+8]=g.movementX;q[t+9]=g.movementY;m=Ga(m);q[t+10]=g.clientX-(m.left|0);q[t+11]=g.clientY-(m.top|0);O(d,e,D.Kf,b)&&g.preventDefault()},lf:c})};function Oc(){return document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement||document.msFullscreenElement}
var Pc=(a,b,c,d,e)=>{D.Yf||(D.Yf=L(276));return E({target:a,ef:e,kf:19,mf:b,hf:d,qf:f=>{var g=D.Yf,m=Oc(),p=!!m;r[g]=p;r[g+1]=D.fullscreenEnabled();var t=p?m:D.Hg,v=t?.id??"";F(Ja(t),g+2,128);F(v,g+130,128);q[g+260>>2]=t?.clientWidth??0;q[g+264>>2]=t?.clientHeight??0;q[g+268>>2]=screen.width;q[g+272>>2]=screen.height;p&&(D.Hg=m);O(d,19,g,b)&&f.preventDefault()},lf:c})},Qc=(a,b,c,d,e)=>{D.Zf||(D.Zf=L(1240));b={target:C(2),Sf:!0,ef:e,kf:d,mf:a,hf:c,qf:f=>{var g=D.Zf;Ka(g,f.gamepad);O(c,d,g,a)&&f.preventDefault()},
lf:b};return E(b)},Rc=(a,b,c,d)=>{D.bg||(D.bg=L(257));return E({target:a,ef:"pointerlockchange",kf:20,mf:b,hf:d,qf:e=>{var f=D.bg,g=document.pointerLockElement;r[f]=!!g;var m=g?.id??"";F(Ja(g),f+1,128);F(m,f+129,128);O(d,20,f,b)&&e.preventDefault()},lf:c})},Sc=(a,b,c,d)=>{D.gg||(D.gg=L(36));a=C(a);return E({target:a,ef:"resize",kf:10,mf:b,hf:d,qf:e=>{if(e.target==a){var f=document.body;if(f){var g=D.gg;q[g>>2]=0;q[g+4>>2]=f.clientWidth;q[g+8>>2]=f.clientHeight;q[g+12>>2]=innerWidth;q[g+16>>2]=innerHeight;
q[g+20>>2]=outerWidth;q[g+24>>2]=outerHeight;q[g+28>>2]=pageXOffset|0;q[g+32>>2]=pageYOffset|0;O(d,10,g,b)&&e.preventDefault()}}},lf:c})},Tc=(a,b,c,d,e,f)=>{D.fg||(D.fg=L(1552));a=C(a);return E({target:a,Sf:f=="touchstart"||f=="touchend",ef:f,kf:e,mf:b,hf:d,qf:g=>{var m={},p=g.touches;for(var t of p)t.og=t.pg=0,m[t.identifier]=t;for(var v of g.changedTouches)v.og=1,m[v.identifier]=v;for(var B of g.targetTouches)m[B.identifier].pg=1;p=D.fg;x[p>>3]=g.timeStamp;r[p+12]=g.ctrlKey;r[p+13]=g.shiftKey;r[p+
14]=g.altKey;r[p+15]=g.metaKey;t=p+16;v=Ga(a);B=0;for(let w of Object.values(m))if(m=t>>2,q[m]=w.identifier,q[m+1]=w.screenX,q[m+2]=w.screenY,q[m+3]=w.clientX,q[m+4]=w.clientY,q[m+5]=w.pageX,q[m+6]=w.pageY,r[t+28]=w.og,r[t+29]=w.pg,q[m+8]=w.clientX-(v.left|0),q[m+9]=w.clientY-(v.top|0),t+=48,++B>31)break;q[p+8>>2]=B;O(d,e,p,b)&&g.preventDefault()},lf:c})},Uc=(a,b,c)=>{var d=Fa[1];D.jg||(D.jg=L(8));return E({target:d,ef:"visibilitychange",kf:21,mf:a,hf:c,qf:e=>{var f=D.jg,g=["hidden","visible","prerender",
"unloaded"].indexOf(document.visibilityState);r[f]=document.hidden;q[f+4>>2]=g;O(c,21,f,a)&&e.preventDefault()},lf:b})},Vc=!1,Wc=!1,Xc=[];function Yc(){function a(){Wc=document.pointerLockElement===h.canvas}if(!Zc){Zc=!0;var b=h.canvas;b&&(document.addEventListener("pointerlockchange",a),h.elementPointerLock&&b.addEventListener("click",c=>{!Wc&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),c.preventDefault())}))}}
function $c(a){var b={antialias:P[135181]>1,depth:P[135173]>0,stencil:P[135174]>0,alpha:P[135172]>0};if(!h.ctx||a!=h.canvas){var c,d={antialias:!1,alpha:!1,Gg:1};if(b)for(var e in b)d[e]=b[e];if(typeof db!="undefined"&&(c=bb(a,d)))var f=Va[c].Rf;f&&(h.ctx=f,cb=Va[c],h.ctx=G=cb?.Rf,Xc.forEach(g=>g()),Yc())}}var ad=!1,Q=void 0,R=void 0;
function bd(a,b){function c(){Vc=!1;var f=d.parentNode;Oc()===f?(d.exitFullscreen=cd,Q&&d.requestPointerLock(),Vc=!0,R?dd():S(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),R?ed():S(d))}Q=a;R=b;typeof Q=="undefined"&&(Q=!0);typeof R=="undefined"&&(R=!1);var d=h.canvas;ad||(ad=!0,document.addEventListener("fullscreenchange",c),document.addEventListener("mozfullscreenchange",c),document.addEventListener("webkitfullscreenchange",c),document.addEventListener("MSFullscreenChange",c));
var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()}
function cd(){if(!Vc)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}var fd=0,gd=0,hd=0,jd=0;function kd(a,b){var c=h.canvas,d=c.getBoundingClientRect();a-=window.scrollX+d.left;b-=window.scrollY+d.top;a*=c.width/d.width;b*=c.height/d.height;return{x:a,y:b}}function ld(a,b){var {x:c,y:d}=kd(a,b);hd=c-fd;jd=d-gd;fd=c;gd=d}
function md(a){Wc?(a.type!="mousemove"&&"mozMovementX"in a?hd=jd=0:(hd=a.movementX||a.mozMovementX||a.webkitMovementX||0,jd=a.movementY||a.mozMovementY||a.webkitMovementY||0),fd+=hd,gd+=jd):a.type==="touchstart"||a.type==="touchend"||a.type==="touchmove"?(a=a.fh,a!==void 0&&kd(a.pageX,a.pageY)):ld(a.pageX,a.pageY)}var nd=[];function od(){var a=h.canvas;nd.forEach(b=>b(a.width,a.height))}function pd(a,b){S(h.canvas,a,b);od()}
function dd(){typeof SDL!="undefined"&&(q[SDL.screen>>2]=y[SDL.screen>>2]|8388608);S(h.canvas);od()}function ed(){typeof SDL!="undefined"&&(q[SDL.screen>>2]=y[SDL.screen>>2]&-8388609);S(h.canvas);od()}
function S(a,b,c){b&&c?(a.kg=b,a.$f=c):(b=a.kg,c=a.$f);var d=b,e=c;if(Oc()===a.parentNode&&typeof screen!="undefined"){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*f)}R?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),typeof a.style!="undefined"&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),typeof a.style!="undefined"&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",
e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var Zc,qd=[null,[],[]];function rd(a,b,c,d,e,f){this.id=a;this.y=this.x=0;this.fullscreen=!1;this.ug=this.tg=0;this.width=b;this.height=c;this.Xf=d;this.Wf=e;this.dg=b;this.cg=c;this.title=f;this.attributes={...P};this.buttons=0;this.keys=[];this.Tf=[];this.Ig=0;this.title=null;this.wf=this.Ef=this.xf=this.Nf=this.sf=this.uf=this.Jf=this.Pf=this.ng=this.Ag=this.zg=this.yg=this.Qf=0}
var Bd=(a,b)=>{sd=a;td=b;if(ud)if(vd||=!0,a==0)wd=function(){setTimeout(xd,Math.max(0,yd+b-performance.now())|0)};else if(a==1)wd=function(){zd(xd)};else{if(!Ad)if(globalThis.scheduler)Ad=scheduler.postTask.bind(scheduler);else{var c=[];addEventListener("message",d=>{d.data==="setimmediate"&&(d.stopPropagation(),c.shift()())},!0);Ad=d=>{c.push(d);postMessage("setimmediate","*")}}wd=function(){Ad(xd)}}},Jd=a=>{function b(){return c<Cd?(Ba(),!1):!0}ud=a;var c=Cd;vd=!1;xd=function(){if(!l)if(Dd.length>
0){var d=Dd.shift();d.Vg(d.Mg);if(Ed){var e=Ed,f=e%1==0?e-1:Math.floor(e);Ed=d.Qg?f:(8*e+(f+.5))/9}h.setStatus&&(d=h.statusMessage||"Please wait...",e=Ed??0,f=Fd.Ug??0,e?e<f?h.setStatus("{message} ({expected - remaining}/{expected})"):h.setStatus(d):h.setStatus(""));b()&&setTimeout(xd,0)}else if(b())if(Gd=Gd+1|0,sd==1&&td>1&&Gd%td!=0)wd();else{sd==0&&(yd=performance.now());a:if(!l){for(d of Hd)if(d()===!1)break a;Ca(a);for(e of Id)e()}b()&&wd()}}},vd=!1,wd=null,Cd=0,ud=null,sd=0,td=0,Gd=0,Dd=[],Hd=
[],Id=[];function Kd(){wd=null;Cd++}function Ld(){Cd++;var a=sd,b=td,c=ud;ud=null;Jd(c);Bd(a,b);wd()}var Md=0;function zd(a){if(globalThis.requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(Md===0)Md=b+1E3/60;else for(;b+2>=Md;)Md+=1E3/60;setTimeout(a,Math.max(Md-b,0))}}
var Fd={},yd,xd,Ad,Ed,U=a=>a<=0||!T?null:T[a-1],Nd=0,V=null,Od=null,T=null,Pd=null,Qd=null,P=null,Rd=null,Sd={131073:0,131074:0,131075:1,131076:1,131077:1,131082:0,135169:8,135170:8,135171:8,135172:8,135173:24,135174:8,135175:0,135176:0,135177:0,135178:0,135179:0,135180:0,135181:0,135182:0,135183:0,139265:196609,139266:1,139267:0,139268:0,139269:0,139270:0,139271:0,139272:0,139276:0},Td=a=>{switch(a){case 32:return 32;case 222:return 39;case 188:return 44;case 173:return 45;case 189:return 45;case 190:return 46;
case 191:return 47;case 48:return 48;case 49:return 49;case 50:return 50;case 51:return 51;case 52:return 52;case 53:return 53;case 54:return 54;case 55:return 55;case 56:return 56;case 57:return 57;case 59:return 59;case 61:return 61;case 187:return 61;case 65:return 65;case 66:return 66;case 67:return 67;case 68:return 68;case 69:return 69;case 70:return 70;case 71:return 71;case 72:return 72;case 73:return 73;case 74:return 74;case 75:return 75;case 76:return 76;case 77:return 77;case 78:return 78;
case 79:return 79;case 80:return 80;case 81:return 81;case 82:return 82;case 83:return 83;case 84:return 84;case 85:return 85;case 86:return 86;case 87:return 87;case 88:return 88;case 89:return 89;case 90:return 90;case 219:return 91;case 220:return 92;case 221:return 93;case 192:return 96;case 27:return 256;case 13:return 257;case 9:return 258;case 8:return 259;case 45:return 260;case 46:return 261;case 39:return 262;case 37:return 263;case 40:return 264;case 38:return 265;case 33:return 266;case 34:return 267;
case 36:return 268;case 35:return 269;case 20:return 280;case 145:return 281;case 144:return 282;case 44:return 283;case 19:return 284;case 112:return 290;case 113:return 291;case 114:return 292;case 115:return 293;case 116:return 294;case 117:return 295;case 118:return 296;case 119:return 297;case 120:return 298;case 121:return 299;case 122:return 300;case 123:return 301;case 124:return 302;case 125:return 303;case 126:return 304;case 127:return 305;case 128:return 306;case 129:return 307;case 130:return 308;
case 131:return 309;case 132:return 310;case 133:return 311;case 134:return 312;case 135:return 313;case 136:return 314;case 96:return 320;case 97:return 321;case 98:return 322;case 99:return 323;case 100:return 324;case 101:return 325;case 102:return 326;case 103:return 327;case 104:return 328;case 105:return 329;case 110:return 330;case 111:return 331;case 106:return 332;case 109:return 333;case 107:return 334;case 16:return 340;case 17:return 341;case 18:return 342;case 91:return 343;case 224:return 343;
case 93:return 348;default:return-1}},Ud=()=>{var a=V,b=0;a.keys[340]&&(b|=1);a.keys[341]&&(b|=2);a.keys[342]&&(b|=4);if(a.keys[343]||a.keys[348])b|=8;return b},Vd=a=>{V&&V.wf&&!a.ctrlKey&&!a.metaKey&&(a=a.charCode,a==0||a>=0&&a<=31||dynCall_vii(V.wf,V.id,a))},Xd=(a,b)=>{if(V){var c=Td(a);if(c!=-1){var d=b&&V.keys[c];V.keys[c]=b;V.Tf[a]=b;V.Ef&&(d&&(b=2),Wd(V.Ef,V.id,c,a,b,Ud()))}}},Zd=()=>{Yd()},$d=()=>{Yd()},ae=a=>{Xd(a.keyCode,1);a.key!="Backspace"&&a.key!="Tab"||a.preventDefault()},be=a=>{Xd(a.keyCode,
0)},ce=()=>{if(V)for(var a=0;a<V.Tf.length;++a)V.Tf[a]&&Xd(a,0)},ee=a=>{if(V){if(a.type==="touchmove"){a.preventDefault();let b=!1;for(let c of a.changedTouches)if(Rd===c.identifier){ld(c.pageX,c.pageY);b=!0;break}if(!b)return}else md(a);a.target==h.canvas&&V.uf&&V.uf&&de(V.uf,V.id,fd,gd)}},fe=a=>{V&&a.target==h.canvas&&V.sf&&dynCall_vii(V.sf,V.id,1)},ge=a=>{V&&a.target==h.canvas&&V.sf&&dynCall_vii(V.sf,V.id,0)},ie=(a,b)=>{if(V&&a.target==h.canvas){var c=0;if(a.type==="touchstart"||a.type==="touchend"||
a.type==="touchcancel"){a.preventDefault();var d=!1;if(Rd===null&&a.type==="touchstart"&&a.targetTouches.length>0)d=a.targetTouches[0],Rd=d.identifier,ld(d.pageX,d.pageY),d=!0;else if(a.type==="touchend"||a.type==="touchcancel")for(let e of a.changedTouches)if(Rd===e.identifier){Rd=null;d=!0;break}if(!d)return}else md(a),c=a.button,c>0&&(c=c==1?2:1);if(b==1){V.buttons|=1<<c;try{a.target.setCapture()}catch(e){}}else V.buttons&=~(1<<c);V.Jf&&he(V.Jf,V.id,c,b,Ud())}},je=a=>{V&&ie(a,1)},ke=a=>{V&&ie(a,
0)},le=a=>{var b=0;switch(a.type){case "DOMMouseScroll":b=a.detail/3;break;case "mousewheel":b=a.wheelDelta/120;break;case "wheel":b=a.deltaY;switch(a.deltaMode){case 0:b/=100;break;case 1:b/=3;break;case 2:b*=80;break;default:n("unrecognized mouse wheel delta mode: "+a.deltaMode)}break;default:n("unrecognized mouse wheel event: "+a.type)}b=-b;b=b==0?0:b>0?Math.max(b,1):Math.min(b,-1);V&&V.Nf&&a.target==h.canvas&&(de(V.Nf,V.id,a.type=="mousewheel"?a.wheelDeltaX:a.deltaX,b),a.preventDefault())},ne=
(a,b,c,d)=>{if(V){var e=!1;Oc()?V.fullscreen||(e=a!=screen.width||b!=screen.height,V.tg=V.x,V.ug=V.y,V.dg=V.width,V.cg=V.height,V.x=V.y=0,V.width=screen.width,V.height=screen.height,V.fullscreen=!0):V.fullscreen==1&&(e=a!=V.dg||b!=V.cg,V.x=V.tg,V.y=V.ug,V.width=V.dg,V.height=V.cg,V.fullscreen=!1);if(e)pd(V.width,V.height);else if(V.width!=a||V.height!=b||V.Xf!=c||V.Wf!=d)V.width=a,V.height=b,V.Xf=c,V.Wf=d,V&&V.Qf&&me(V.Qf,V.id,V.width,V.height),V&&V.ng&&me(V.ng,V.id,V.Xf,V.Wf)}},W={},oe=[],pe=null,
Yd=()=>{if(Gd!==pe||!Gd){oe=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads||[];pe=Gd;for(var a=0;a<oe.length;++a){var b=oe[a];if(b){W[a]||(fa("glfw joystick connected:",a),W[a]={id:ec(b.id),Pg:b.buttons.length,Ng:b.axes.length,buttons:L(b.buttons.length),axes:L(b.axes.length*4)});for(var c=W[a],d=0;d<b.buttons.length;++d)r[c.buttons+d]=b.buttons[d].pressed;for(d=0;d<b.axes.length;++d)u[c.axes+d*4>>2]=b.axes[d]}else W[a]&&(fa("glfw joystick disconnected",a),qe(W[a].id),qe(W[a].buttons),
qe(W[a].axes),delete W[a])}}},re=a=>{if(V&&V.xf&&a.dataTransfer&&a.dataTransfer.files&&a.dataTransfer.files.length!=0)return a.preventDefault(),!1},se=a=>{if(V&&V.xf)return a.preventDefault(),!1};
function te(a,b){function c(){Vc=!1;var f=d.parentNode;Oc()===f?(d.exitFullscreen=cd,Q&&d.requestPointerLock(),Vc=!0,R?dd():(S(d),od())):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),R?ed():(S(d),od()))}Q=a;R=b;typeof Q=="undefined"&&(Q=!0);typeof R=="undefined"&&(R=!1);var d=h.canvas;ad||(ad=!0,document.addEventListener("fullscreenchange",c),document.addEventListener("mozfullscreenchange",c),document.addEventListener("webkitfullscreenchange",c),document.addEventListener("MSFullscreenChange",
c));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()}
function ue(a,b,c){var d=ve()?Od:1;b&&c?(a.kg=b,a.$f=c):(b=a.kg,c=a.$f);var e=b,f=c;if(Oc()===a.parentNode&&typeof screen!="undefined"){var g=Math.min(screen.width/e,screen.height/f);e=Math.round(e*g);f=Math.round(f*g)}R&&(b=e,c=f);e=Math.floor(b*d);d=Math.floor(c*d);a.width!=e&&(a.width=e);a.height!=d&&(a.height=d);typeof a.style!="undefined"&&(ve()?(a.style.setProperty("width",b+"px","important"),a.style.setProperty("height",c+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height")))}
function we(a,b){var c=h.canvas.getBoundingClientRect();a-=window.scrollX+c.left;b-=window.scrollY+c.top;!ve()&&V&&(a*=V.width/c.width,b*=V.height/c.height);return{x:a,y:b}}function xe(){return typeof devicePixelRatio=="number"&&devicePixelRatio||1}function ve(){return V?V.attributes[139276]>0:!1}function ye(){V&&(S(h.canvas,V.width,V.height),od())}function ze(){Od=xe();V&&V.Pf&&Ae(V.Pf,V.id,Od,Od);ye()}var Be=a=>{try{a()}catch(b){n(b)}};
function Ce(a){var b=(...c)=>{De.push(a);try{return a(...c)}finally{l||(De.pop(),X&&Y===1&&De.length===0&&(Y=0,Be(Ee),typeof Fibers!="undefined"&&Fibers.gh()))}};Fe.set(a,b);return b}var Y=0,X=null,Ge=0,De=[],He=new Map,Ie=new Map,Fe=new Map,Je=0,Ke=null,Le=[];function Me(){var a=L(4108),b=a+12;y[a>>2]=b;y[a+4>>2]=b+4096;b=De[0];if(!He.has(b)){var c=Je++;He.set(b,c);Ie.set(c,b)}b=He.get(b);q[a+8>>2]=b;return a}function Ne(){var a=Ie.get(q[X+8>>2]);a=Fe.get(a);return Ca(a)}
function Oe(a){if(!l){if(Y===0){var b=!1,c=!1;a((d=0)=>{if(!l&&(Ge=d,b=!0,c)){Y=2;Be(()=>Pe(X));typeof Fd!="undefined"&&ud&&Ld();d=!1;try{var e=Ne()}catch(m){e=m,d=!0}var f=!1;if(!X){var g=Ke;g&&(Ke=null,(d?g.reject:g.resolve)(e),f=!0)}if(d&&!f)throw e;}});c=!0;b||(Y=1,X=Me(),typeof Fd!="undefined"&&ud&&Kd(),Be(()=>Qe(X)))}else Y===2?(Y=0,Be(Re),qe(X),X=null,Le.forEach(Ca)):n(`invalid state: ${Y}`);return Ge}}var Se=a=>Oe(async b=>{b(await a())});for(let a=0;a<32;++a)Jb.push(Array(a));
for(var Te=new Float32Array(288),Z=0;Z<=288;++Z)N[Z]=Te.subarray(0,Z);var Ue=new Int32Array(288);for(Z=0;Z<=288;++Z)yc[Z]=Ue.subarray(0,Z);h.requestAnimationFrame=zd;h.pauseMainLoop=Kd;h.resumeMainLoop=Ld;h.noExitRuntime&&(ua=h.noExitRuntime);h.print&&(fa=h.print);h.printErr&&(k=h.printErr);h.arguments&&(aa=h.arguments);h.thisProgram&&(ba=h.thisProgram);var Ve=h.preInit;if(Ve)for(typeof Ve=="function"&&(h.preInit=Ve=[Ve]);Ve.length>0;)Ve.shift()();
var $e={50238:()=>{if(document.fullscreenElement)return 1},50284:()=>h.canvas.width,50316:()=>parseInt(h.canvas.style.width),50364:()=>{document.exitFullscreen()},50391:()=>{setTimeout(function(){h.requestFullscreen(!1,!1)},100)},50463:()=>{if(document.fullscreenElement)return 1},50509:()=>h.canvas.width,50541:()=>screen.width,50566:()=>{document.exitFullscreen()},50593:a=>{var b=A(a);setTimeout(function(){h.requestFullscreen(!1,!0);setTimeout(function(){document.querySelector(b).style.width="unset"},
100)},100)},50787:()=>window.innerWidth,50813:()=>window.innerHeight,50840:()=>{if(document.fullscreenElement)return 1},50886:()=>h.canvas.width,50918:()=>parseInt(h.canvas.style.width),50966:()=>{if(document.fullscreenElement)return 1},51012:()=>h.canvas.width,51044:()=>screen.width,51069:()=>window.innerWidth,51095:()=>window.innerHeight,51122:()=>{if(document.fullscreenElement)return 1},51168:()=>h.canvas.width,51200:()=>screen.width,51225:()=>{document.exitFullscreen()},51252:()=>{if(document.fullscreenElement)return 1},
51298:()=>h.canvas.width,51330:()=>parseInt(h.canvas.style.width),51378:()=>{document.exitFullscreen()},51405:a=>{h.canvas.style.opacity=a},51443:()=>screen.width,51468:()=>screen.height,51494:()=>window.screenX,51521:()=>window.screenY,51548:()=>window.devicePixelRatio,51584:a=>{navigator.clipboard.writeText(A(a))},51637:a=>{h.canvas.style.cursor=A(a)},51688:()=>{h.canvas.style.cursor="none"},51725:(a,b,c,d)=>{try{navigator.getGamepads()[a].vibrationActuator.playEffect("dual-rumble",{startDelay:0,
duration:d,weakMagnitude:b,strongMagnitude:c})}catch(e){try{navigator.getGamepads()[a].Ze[0].Zg(c,d)}catch(f){}}},51981:a=>{h.canvas.style.cursor=A(a)},52032:()=>{if(document.pointerLockElement)return 1},52079:()=>{if(document.fullscreenElement)return 1},52125:()=>window.innerWidth,52151:()=>window.innerHeight,52178:(a,b,c,d,e)=>{if(typeof window==="undefined"||(window.AudioContext||window.webkitAudioContext)===void 0)return 0;if(typeof window.Ze==="undefined"){window.Ze={Mf:0};window.Ze.df={};window.Ze.df.Lf=
a;window.Ze.df.capture=b;window.Ze.df.Uf=c;window.Ze.tf={};window.Ze.tf.stopped=d;window.Ze.tf.sg=e;let f=window.Ze;f.bf=[];f.Jg=function(g){for(var m=0;m<f.bf.length;++m)if(f.bf[m]==null)return f.bf[m]=g,m;f.bf.push(g);return f.bf.length-1};f.xg=function(g){for(f.bf[g]=null;f.bf.length>0;)if(f.bf[f.bf.length-1]==null)f.bf.pop();else break};f.hh=function(g){for(var m=0;m<f.bf.length;++m)if(f.bf[m]==g)return f.xg(m)};f.Cf=function(g){return f.bf[g]};f.ig=["touchend","click"];f.unlock=function(){for(var g=
0;g<f.bf.length;++g){var m=f.bf[g];m!=null&&m.gf!=null&&m.state===f.tf.sg&&m.gf.resume().then(()=>{We(m.qg)},p=>{console.error("Failed to resume audiocontext",p)})}f.ig.map(function(p){document.removeEventListener(p,f.unlock,!0)})};f.ig.map(function(g){document.addEventListener(g,f.unlock,!0)})}window.Ze.Mf+=1;return 1},54356:()=>{typeof window.Ze!=="undefined"&&(window.Ze.ig.map(function(a){document.removeEventListener(a,window.Ze.unlock,!0)}),--window.Ze.Mf,window.Ze.Mf===0&&delete window.Ze)},
54660:()=>navigator.mediaDevices!==void 0&&navigator.mediaDevices.getUserMedia!==void 0,54764:()=>{try{var a=new (window.AudioContext||window.webkitAudioContext),b=a.sampleRate;a.close();return b}catch(c){return 0}},54935:(a,b,c,d,e,f)=>{if(typeof window.Ze==="undefined")return-1;var g={},m={};a==window.Ze.df.Lf&&c!=0&&(m.sampleRate=c);g.gf=new (window.AudioContext||window.webkitAudioContext)(m);g.gf.suspend();g.state=window.Ze.tf.stopped;c=0;a!=window.Ze.df.Lf&&(c=b);g.rf=g.gf.createScriptProcessor(d,
c,b);g.rf.onaudioprocess=function(p){if(g.Df==null||g.Df.length==0)g.Df=new Float32Array(u.buffer,e,d*b);if(a==window.Ze.df.capture||a==window.Ze.df.Uf){for(var t=0;t<b;t+=1)for(var v=p.inputBuffer.getChannelData(t),B=g.Df,w=0;w<d;w+=1)B[w*b+t]=v[w];Xe(f,d,e)}if(a==window.Ze.df.Lf||a==window.Ze.df.Uf)for(Ye(f,d,e),t=0;t<p.outputBuffer.numberOfChannels;++t)for(v=p.outputBuffer.getChannelData(t),B=g.Df,w=0;w<d;w+=1)v[w]=B[w*b+t];else for(t=0;t<p.outputBuffer.numberOfChannels;++t)p.outputBuffer.getChannelData(t).fill(0)};
a!=window.Ze.df.capture&&a!=window.Ze.df.Uf||navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(function(p){g.Of=g.gf.createMediaStreamSource(p);g.Of.connect(g.rf);g.rf.connect(g.gf.destination)}).catch(function(p){console.log("Failed to get user media: "+p)});a==window.Ze.df.Lf&&g.rf.connect(g.gf.destination);g.qg=f;return window.Ze.Jg(g)},57812:a=>window.Ze.Cf(a).gf.sampleRate,57885:a=>{a=window.Ze.Cf(a);a.rf!==void 0&&(a.rf.onaudioprocess=function(){},a.rf.disconnect(),a.rf=void 0);
a.Of!==void 0&&(a.Of.disconnect(),a.Of=void 0);a.gf.close();a.gf=void 0;a.qg=void 0},58285:a=>{window.Ze.xg(a)},58335:a=>{a=window.Ze.Cf(a);a.gf.resume();a.state=window.Ze.tf.sg},58474:a=>{a=window.Ze.Cf(a);a.gf.suspend();a.state=window.Ze.tf.stopped}},af,qe,L,We,Xe,Ye,bf,cf,dynCall_vii,me,Ae,Wd,he,de,O,dynCall_iii,dynCall_vi,dynCall_v,Qe,Ee,Pe,Re,df,ef={ia:function(a,b){F("#"+h.canvas.id,a,b)},a:(a,b,c,d)=>n(`Assertion failed: ${A(a)}, at: `+[b?A(b):"unknown filename",c,d?A(d):"unknown function"]),
cb:()=>{},P:function(){return 0},Wa:()=>{},Za:function(){return 0},_a:function(){},Ua:()=>n(""),Ta:()=>{ua=!1;xa=0},Pa:(a,b)=>{ya[a]&&(clearTimeout(ya[a].id),delete ya[a]);if(!b)return 0;var c=setTimeout(()=>{delete ya[a];Ca(()=>bf(a,performance.now()))},b);ya[a]={id:c,eh:b};return 0},bb:function(a,b,c){if(!(a>=0&&a<=3))return 28;sa[c>>3]=BigInt(Math.round((a===0?Date.now():performance.now())*1E3*1E3));return 0},B:(a,b,c)=>{b=Ea(b,c);return $e[a](...b)},d:(a,b,c)=>{b=Ea(b,c);return $e[a](...b)},ab:()=>
Date.now(),le:(a,b,c)=>{a=C(a);if(!a)return-4;a=Ga(a);x[b>>3]=a.width;x[c>>3]=a.height;return 0},ja:(a,b)=>{if(a<0||a>=D.Ff.length)return-5;if(!D.Ff[a])return-7;Ka(b,D.Ff[a]);return 0},D:()=>performance.now(),ka:()=>D.Ff.length,Rd:eb,Qd:fb,ge:(a,b)=>{G.jf.beginQueryEXT(a,J[b])},Pd:gb,Od:hb,Nd:ib,Md:jb,Ld:kb,Zd:a=>{G.bindVertexArray(Ua[a])},Kd:(a,b,c,d)=>G.blendColor(a,b,c,d),Jd:lb,Id:mb,Hd:nb,Gd:ob,Fd:pb,Ed:qb,Dd:rb,Cd:sb,Bd:tb,Ad:ub,zd:a=>G.clearStencil(a),eb:(a,b)=>{G.Dg.clipControlEXT(a,b)},yd:(a,
b,c,d)=>{G.colorMask(!!a,!!b,!!c,!!d)},xd:vb,wd:wb,vd:(a,b,c,d,e,f,g,m,p)=>{G.compressedTexSubImage2D(a,b,c,d,e,f,g,z.subarray(p,p+m))},ud:(a,b,c,d,e,f,g,m)=>G.copyTexImage2D(a,b,c,d,e,f,g,m),td:(a,b,c,d,e,f,g,m)=>G.copyTexSubImage2D(a,b,c,d,e,f,g,m),sd:xb,rd:yb,qd:zb,pd:Ab,od:(a,b)=>{for(var c=0;c<a;++c){var d=q[b+c*4>>2],e=Ra[d];e&&(G.deleteFramebuffer(e),e.name=0,Ra[d]=null)}},nd:Bb,ie:(a,b)=>{for(var c=0;c<a;c++){var d=q[b+c*4>>2],e=J[d];e&&(G.jf.deleteQueryEXT(e),J[d]=null)}},md:(a,b)=>{for(var c=
0;c<a;c++){var d=q[b+c*4>>2],e=Sa[d];e&&(G.deleteRenderbuffer(e),e.name=0,Sa[d]=null)}},ld:Cb,kd:Db,Yd:(a,b)=>{for(var c=0;c<a;c++){var d=q[b+c*4>>2];G.deleteVertexArray(Ua[d]);Ua[d]=null}},jd:Eb,id:a=>{G.depthMask(!!a)},hd:(a,b)=>G.depthRange(a,b),gd:Fb,fd:Gb,dd:Hb,cd:Ib,Ud:(a,b,c,d)=>{G.drawArraysInstanced(a,b,c,d)},Vd:(a,b)=>{for(var c=Jb[a],d=0;d<a;d++)c[d]=q[b+d*4>>2];G.drawBuffers(c)},bd:Kb,Td:(a,b,c,d,e)=>{G.drawElementsInstanced(a,b,c,d,e)},ad:Lb,$c:Mb,fe:a=>{G.jf.endQueryEXT(a)},_c:()=>G.finish(),
Zc:()=>G.flush(),Yc:Nb,Xc:Ob,Wc:Pb,Vc:Qb,Tc:Rb,je:(a,b)=>{for(var c=0;c<a;c++){var d=G.jf.createQueryEXT();if(!d){for(K||=1282;c<a;)q[b+c++*4>>2]=0;break}var e=Za(J);d.name=e;J[e]=d;q[b+c*4>>2]=e}},Sc:Sb,Rc:Tb,Xd:(a,b)=>{$a(a,b,"createVertexArray",Ua)},Uc:a=>G.generateMipmap(a),Qc:(a,b,c,d,e,f,g)=>Ub("getActiveAttrib",a,b,c,d,e,f,g),Pc:(a,b,c,d,e,f,g)=>Ub("getActiveUniform",a,b,c,d,e,f,g),Oc:(a,b,c,d)=>{a=G.getAttachedShaders(H[a]);var e=a.length;e>b&&(e=b);q[c>>2]=e;for(b=0;b<e;++b)q[d+b*4>>2]=I.indexOf(a[b])},
Nc:Vb,Mc:(a,b)=>Wb(a,b,4),Kc:(a,b,c)=>{c?q[c>>2]=G.getBufferParameter(a,b):K||=1281},Jc:()=>{var a=G.getError()||K;K=0;return a},Ic:Xb,Hc:(a,b,c,d)=>{a=G.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;q[d>>2]=a},Gc:(a,b)=>Wb(a,b,0),Ec:Yb,Fc:Zb,$d:$b,ce:ac,_d:$b,ae:ac,de:(a,b,c)=>{c?q[c>>2]=G.jf.getQueryEXT(a,b):K||=1281},Dc:(a,b,c)=>{c?q[c>>2]=G.getRenderbufferParameter(a,b):K||=1281},Bc:bc,Ac:(a,b,c,d)=>{a=G.getShaderPrecisionFormat(a,
b);q[c>>2]=a.rangeMin;q[c+4>>2]=a.rangeMax;q[d>>2]=a.precision},zc:(a,b,c,d)=>{if(a=G.getShaderSource(I[a]))b=b>0&&d?F(a,d,b):0,c&&(q[c>>2]=b)},Cc:cc,yc:hc,xc:(a,b,c)=>{c?u[c>>2]=G.getTexParameter(a,b):K||=1281},wc:(a,b,c)=>{c?q[c>>2]=G.getTexParameter(a,b):K||=1281},tc:kc,vc:(a,b,c)=>{lc(a,b,c,2)},uc:(a,b,c)=>{lc(a,b,c,0)},qc:(a,b,c)=>{c?q[c>>2]=G.getVertexAttribOffset(a,b):K||=1281},sc:(a,b,c)=>{mc(a,b,c,2)},rc:(a,b,c)=>{mc(a,b,c,5)},pc:(a,b)=>G.hint(a,b),oc:a=>(a=Qa[a])?G.isBuffer(a):0,nc:a=>G.isEnabled(a),
mc:a=>(a=Ra[a])?G.isFramebuffer(a):0,lc:a=>(a=H[a])?G.isProgram(a):0,he:a=>(a=J[a])?G.jf.isQueryEXT(a):0,kc:a=>(a=Sa[a])?G.isRenderbuffer(a):0,jc:a=>(a=I[a])?G.isShader(a):0,ic:a=>(a=Ta[a])?G.isTexture(a):0,Wd:a=>(a=Ua[a])?G.isVertexArray(a):0,hc:a=>G.lineWidth(a),gc:nc,fc:oc,db:(a,b)=>{G.Kg.polygonModeWEBGL(a,b)},ec:(a,b)=>G.polygonOffset(a,b),fb:(a,b,c)=>{G.Eg.polygonOffsetClampEXT(a,b,c)},ee:(a,b)=>{G.jf.queryCounterEXT(J[a],b)},dc:qc,cc:()=>{},bc:rc,ac:(a,b)=>{G.sampleCoverage(a,!!b)},$b:sc,_b:()=>
{K||=1280},Zb:tc,Yb:(a,b,c)=>G.stencilFunc(a,b,c),Xb:(a,b,c,d)=>G.stencilFuncSeparate(a,b,c,d),Wb:a=>G.stencilMask(a),Vb:(a,b)=>G.stencilMaskSeparate(a,b),Ub:(a,b,c)=>G.stencilOp(a,b,c),Tb:(a,b,c,d)=>G.stencilOpSeparate(a,b,c,d),Sb:uc,Rb:(a,b,c)=>G.texParameterf(a,b,c),Qb:(a,b,c)=>{G.texParameterf(a,b,u[c>>2])},Pb:vc,Nb:(a,b,c)=>{G.texParameteri(a,b,q[c>>2])},Mb:(a,b,c,d,e,f,g,m,p)=>{p=p?pc(m,g,e,f,p):null;G.texSubImage2D(a,b,c,d,e,f,g,m,p)},Lb:(a,b)=>{G.uniform1f(M(G.af,a),b)},Kb:wc,Jb:xc,Ib:zc,
Hb:(a,b,c)=>{G.uniform2f(M(G.af,a),b,c)},Gb:Ac,Fb:(a,b,c)=>{G.uniform2i(M(G.af,a),b,c)},Eb:Bc,Cb:(a,b,c,d)=>{G.uniform3f(M(G.af,a),b,c,d)},Bb:Cc,Ab:(a,b,c,d)=>{G.uniform3i(M(G.af,a),b,c,d)},zb:Dc,yb:Ec,xb:Fc,wb:(a,b,c,d,e)=>{G.uniform4i(M(G.af,a),b,c,d,e)},vb:Gc,ub:(a,b,c,d)=>{if(b<=72){b*=4;for(var e=N[b],f=0;f<b;f+=4)e[f]=u[d+4*f>>2],e[f+1]=u[d+(4*f+4)>>2],e[f+2]=u[d+(4*f+8)>>2],e[f+3]=u[d+(4*f+12)>>2]}else e=u.subarray(d>>2,d+b*16>>2);G.uniformMatrix2fv(M(G.af,a),!!c,e)},tb:(a,b,c,d)=>{if(b<=32){b*=
9;for(var e=N[b],f=0;f<b;f+=9)e[f]=u[d+4*f>>2],e[f+1]=u[d+(4*f+4)>>2],e[f+2]=u[d+(4*f+8)>>2],e[f+3]=u[d+(4*f+12)>>2],e[f+4]=u[d+(4*f+16)>>2],e[f+5]=u[d+(4*f+20)>>2],e[f+6]=u[d+(4*f+24)>>2],e[f+7]=u[d+(4*f+28)>>2],e[f+8]=u[d+(4*f+32)>>2]}else e=u.subarray(d>>2,d+b*36>>2);G.uniformMatrix3fv(M(G.af,a),!!c,e)},sb:Hc,rb:Ic,qb:a=>{G.validateProgram(H[a])},pb:(a,b)=>G.vertexAttrib1f(a,b),ob:(a,b)=>{G.vertexAttrib1f(a,u[b>>2])},nb:(a,b,c)=>G.vertexAttrib2f(a,b,c),mb:(a,b)=>{G.vertexAttrib2f(a,u[b>>2],u[b+
4>>2])},lb:(a,b,c,d)=>G.vertexAttrib3f(a,b,c,d),kb:(a,b)=>{G.vertexAttrib3f(a,u[b>>2],u[b+4>>2],u[b+8>>2])},jb:(a,b,c,d,e)=>G.vertexAttrib4f(a,b,c,d,e),ib:(a,b)=>{G.vertexAttrib4f(a,u[b>>2],u[b+4>>2],u[b+8>>2],u[b+12>>2])},Sd:(a,b)=>{G.vertexAttribDivisor(a,b)},hb:Jc,gb:Kc,Qa:()=>{n("OOM")},la:Lc,Ae:(a,b,c,d)=>Mc(a,b,c,d,12,"blur"),oa:(a,b,c)=>{a=C(a);if(!a)return-4;a.width=b;a.height=c;return 0},we:(a,b,c,d)=>Nc(a,b,c,d,4,"click"),ze:(a,b,c,d)=>Mc(a,b,c,d,13,"focus"),Be:(a,b,c,d)=>{if(!D.fullscreenEnabled())return-1;
a=C(a);if(!a)return-4;Pc(a,b,c,d,"webkitfullscreenchange");return Pc(a,b,c,d,"fullscreenchange")},pe:(a,b,c)=>Lc()?-1:Qc(a,b,c,26,"gamepadconnected"),oe:(a,b,c)=>Lc()?-1:Qc(a,b,c,27,"gamepaddisconnected"),ue:(a,b,c,d)=>Nc(a,b,c,d,8,"mousemove"),ve:(a,b,c,d)=>document.body?.requestPointerLock?(a=C(a))?Rc(a,b,c,d):-4:-1,xe:(a,b,c,d)=>Sc(a,b,c,d),qe:(a,b,c,d)=>Tc(a,b,c,d,25,"touchcancel"),se:(a,b,c,d)=>Tc(a,b,c,d,23,"touchend"),re:(a,b,c,d)=>Tc(a,b,c,d,24,"touchmove"),te:(a,b,c,d)=>Tc(a,b,c,d,22,"touchstart"),
ye:(a,b,c)=>Uc(a,b,c),pa:a=>document.title=A(a),ra:function(a){return Se(()=>new Promise(b=>setTimeout(b,a)))},Ge:a=>{ha=a;Aa(a)},Q:()=>52,Ya:()=>52,Va:function(){return 70},Xa:(a,b,c,d)=>{for(var e=0,f=0;f<c;f++){var g=y[b>>2],m=y[b+4>>2];b+=8;for(var p=0;p<m;p++){var t=a,v=z[g+p],B=qd[t];v===0||v===10?(t=t===1?fa:k,v=wa(B,0),v=va.decode(B.buffer?B.subarray(0,v):new Uint8Array(B.slice(0,v))),t(v),B.length=0):B.push(v)}e+=m}y[d>>2]=e;return 0},W:eb,I:fb,h:gb,c:hb,i:ib,K:jb,n:kb,o:lb,Db:mb,l:nb,Ob:ob,
t:pb,z:qb,Ha:rb,R:sb,S:tb,Oa:ub,Ea:vb,Ma:wb,Ca:xb,Ga:yb,ed:zb,r:Ab,M:Bb,s:Cb,L:Db,$a:Eb,y:Fb,U:Gb,w:Hb,me:Ib,be:Kb,E:Lb,j:Mb,C:Nb,v:Ob,Sa:Pb,u:Qb,Ia:Rb,La:Sb,O:Tb,f:Vb,Lc:Xb,Aa:Yb,H:Zb,Da:bc,J:cc,q:hc,e:kc,Ba:nc,Na:oc,Ja:qc,Ka:rc,T:sc,Fa:tc,N:uc,m:vc,za:wc,ea:xc,sa:zc,ya:Ac,va:Bc,xa:Cc,ua:Dc,na:Ec,wa:Fc,ta:Gc,p:Hc,x:Ic,k:Jc,A:Kc,F:(a,b,c,d)=>{var e;for(e=0;e<T.length&&T[e]!==null;e++);e>0&&n("glfwCreateWindow only supports one window at time currently");var f=e+1;if(a<=0||b<=0)f=0;else{d?bd():pd(a,
b);for(e=0;e<T.length&&T[e]==null;e++);d=h.canvas;var g=P[139265]>0;e==T.length&&(g?$c(d):Yc());!h.ctx&&g?f=0:(a=new rd(f,a,b,d.width,d.height,c),f-1==T.length?T.push(a):T[f-1]=a,V=a,ye(),f=a.id)}return f},fa:()=>{P={...Sd}},ke:a=>{a:{if(a=U(a)){a.yg&&dynCall_vi(a.yg,a.id);T[a.id-1]=null;V.id==a.id&&(V=null);for(a of T)if(a!==null){a=void 0;break a}delete h.ctx}a=void 0}return a},G:()=>1,b:()=>performance.now()/1E3-Pd,da:(a,b)=>q[b>>2]=0,ga:()=>{if(T)return 1;Pd=performance.now()/1E3;P={...Sd};T=
[];V=null;Od=xe();window.addEventListener("gamepadconnected",Zd,!0);window.addEventListener("gamepaddisconnected",$d,!0);window.addEventListener("keydown",ae,!0);window.addEventListener("keypress",Vd,!0);window.addEventListener("keyup",be,!0);window.addEventListener("blur",ce,!0);Qd=window.matchMedia("(resolution: "+xe()+"dppx)");Qd.addEventListener("change",ze);var a=h.canvas;a.addEventListener("touchmove",ee,!0);a.addEventListener("touchstart",je,!0);a.addEventListener("touchcancel",ke,!0);a.addEventListener("touchend",
ke,!0);a.addEventListener("mousemove",ee,!0);a.addEventListener("mousedown",je,!0);a.addEventListener("mouseup",ke,!0);a.addEventListener("wheel",le,!0);a.addEventListener("mousewheel",le,!0);a.addEventListener("mouseenter",fe,!0);a.addEventListener("mouseleave",ge,!0);a.addEventListener("drop",re,!0);a.addEventListener("dragover",se,!0);bd=te;kd=we;S=ue;nd.push((b,c)=>{if(ve()){var d=h.canvas;ne(d.clientWidth,d.clientHeight,b,c)}else ne(b,c,b,c)});return 1},Ce:()=>0,Y:(a,b)=>{if(a=U(a)){var c=a.wf;
a.wf=b;b=c}else b=null;return b},De:(a,b)=>{a=U(a);if(!a)return null;var c=a.sf;a.sf=b;return c},Fe:(a,b)=>{if(a=U(a)){var c=a.uf;a.uf=b;b=c}else b=null;return b},$:(a,b)=>{if(a=U(a)){var c=a.xf;a.xf=b;b=c}else b=null;return b},ha:a=>{var b=Nd;Nd=a;return b},Z:(a,b)=>{if(a=U(a)){var c=a.Ef;a.Ef=b;b=c}else b=null;return b},X:(a,b)=>{if(a=U(a)){var c=a.Jf;a.Jf=b;b=c}else b=null;return b},Ee:(a,b)=>{if(a=U(a)){var c=a.Nf;a.Nf=b;b=c}else b=null;return b},_:(a,b)=>{a=U(a);if(!a)return null;var c=a.Pf;
a.Pf=b;return c},aa:(a,b)=>{a=U(a);if(!a)return null;var c=a.zg;a.zg=b;return c},ba:(a,b)=>{a=U(a);if(!a)return null;var c=a.Ag;a.Ag=b;return c},ne:(a,b)=>{if(a=U(a))a.Ig=b},qa:(a,b,c)=>{(a=U(a))&&V.id==a.id&&pd(b,c)},ca:(a,b)=>{if(a=U(a)){var c=a.Qf;a.Qf=b;b=c}else b=null;return b},ma:()=>{},V:()=>{window.removeEventListener("gamepadconnected",Zd,!0);window.removeEventListener("gamepaddisconnected",$d,!0);window.removeEventListener("keydown",ae,!0);window.removeEventListener("keypress",Vd,!0);window.removeEventListener("keyup",
be,!0);window.removeEventListener("blur",ce,!0);var a=h.canvas;a.removeEventListener("touchmove",ee,!0);a.removeEventListener("touchstart",je,!0);a.removeEventListener("touchcancel",ke,!0);a.removeEventListener("touchend",ke,!0);a.removeEventListener("mousemove",ee,!0);a.removeEventListener("mousedown",je,!0);a.removeEventListener("mouseup",ke,!0);a.removeEventListener("wheel",le,!0);a.removeEventListener("mousewheel",le,!0);a.removeEventListener("mouseenter",fe,!0);a.removeEventListener("mouseleave",
ge,!0);a.removeEventListener("drop",re,!0);a.removeEventListener("dragover",se,!0);Qd&&Qd.removeEventListener("change",ze);a.width=a.height=1;V=T=null},g:(a,b)=>{P[a]=b},Ra:Aa};function ff(a=[]){var b=af;a.unshift(ba);var c=a.length,d=cf((c+1)*4),e=d,f;for(f of a){a=y;var g=e>>2,m=f,p=dc(m)+1,t=cf(p);F(m,t,p);a[g]=t;e+=4}y[e>>2]=0;try{var v=b(c,d);ha=v;Aa(v)}catch(B){za(B)}}
async function gf(){var a=aa;ia();var b=h.setStatus;b&&(b("Running..."),await new Promise(c=>setTimeout(c,1)),setTimeout(b,1,""));l||(hf.Ie(),h.onRuntimeInitialized?.(),h.noInitialRun||ff(a),ka())}var hf;
(async function(){function a(d){var e=hf=d.exports;d={};for(let [f,g]of Object.entries(e))typeof g=="function"?(e=Ce(g),d[f]=e):d[f]=g;d=hf=d;af=h._main=d.Je;qe=d.Ke;L=d.Le;We=h._ma_device__on_notification_unlocked=d.Me;h._ma_malloc_emscripten=d.Ne;h._ma_free_emscripten=d.Oe;Xe=h._ma_device_process_pcm_frames_capture__webaudio=d.Pe;Ye=h._ma_device_process_pcm_frames_playback__webaudio=d.Qe;bf=d.Re;cf=d.Se;dynCall_vii=d.Te;me=d.Ue;Ae=d.Ve;Wd=d.We;he=d.Xe;de=d.Ye;O=d._e;dynCall_iii=d.$e;dynCall_vi=
d.ff;dynCall_v=d.nf;Qe=d.yf;Ee=d.zf;Pe=d.Af;Re=d.Bf;df=d.He;d=df.buffer;r=new Int8Array(d);ra=new Int16Array(d);z=new Uint8Array(d);ta=new Uint16Array(d);q=new Int32Array(d);y=new Uint32Array(d);u=new Float32Array(d);x=new Float64Array(d);sa=new BigInt64Array(d);new BigUint64Array(d);return hf}var b={a:ef},c=h.instantiateWasm;if(c)return new Promise(d=>{c(b,e=>d(a(e)))});ma??=h.locateFile?h.locateFile("index.wasm",da):da+"index.wasm";return function(d){return a(d.instance)}(await pa(b))})().then(()=>
gf());
