# Site settings ...
uri: alex.kaskaso.li
url: https://alex.kaskaso.li
name: Alex Kaskasoli
title: alxk's blog
email: alex@kaskaso.li
author: alxk
baseurl: ""
keywords: "hacking, security, devops, devsecops, kubernetes"
description: "alxk is a security and platform engineer with a decade in the field. He built the original cybersecurity safety evaluations framework at Google DeepMind, where he also threat modelled AI deployments and worked on adversarial testing of image and text watermarking for generative models. He previously led the platform and security team at TrueLayer."
social_username: serain
github_username: serain
twitter_username: alxk7i
linkedin_username: alexkaskasoli

  # Build settings ...
sass:
  style: compressed
markdown: kramdown
highlighter: rouge
auto_ids: true
encoding: "utf-8"
paginate: 10
permalink: /post/:title
paginate_path: "/page/:num/"

  # Plugins ...
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
    # - jekyll-crosspost-to-medium
