# Site settings ...
uri: domain.com
url: https://domain.com
name: Alexandre Kaskasoli
title: alxk's blog
email: example@domain.com
author: alxk
baseurl: ""
keywords: "hacking, security, devops, devsecops, kubernetes"
description: "alxk's blog and security write-ups"
social_username: serain

# Build settings ...
sass:
  style: compressed
markdown: kramdown
encoding: "utf-8"
paginate: 5
permalink: /post/:title
paginate_path: "/page/:num/"

# Plugins ...
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
