# Site settings ...
uri: alex.kaskaso.li
url: https://alex.kaskaso.li
name: Alex Kaskasoli
title: alxk's blog
email: alex@kaskaso.li
author: alxk
baseurl: ""
keywords: "hacking, security, devops, devsecops, kubernetes"
description: "alxk is a Security Consultant. He's into DevOps, writing tools and learning how to leverage new developments in the tech world. During downtime alxk travels a bit randomly around the world, and reads History and hard SciFi."
social_username: serain
github_username: serain
twitter_username: _alxk
linkedin_username: alexkaskasoli

# Build settings ...
sass:
  style: compressed
markdown: kramdown
highlighter: rouge
auto_ids: true
encoding: "utf-8"
paginate: 5
permalink: /post/:title
paginate_path: "/page/:num/"

# Plugins ...
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
  - jekyll-crosspost-to-medium
