# Site settings ...
uri: alex.kaskaso.li
url: https://alex.kaskaso.li
name: Alex Kaskasoli
title: alxk's blog
email: alex@kaskaso.li
author: alxk
baseurl: ""
keywords: "hacking, security, devops, devsecops, kubernetes"
description: "alxk is an infrastructure and security engineer. He likes writing tools, automating security and following the tech scene. During downtime he travels a bit randomly and reads history and hard SciFi."
social_username: serain
github_username: serain
twitter_username: alxk7i
linkedin_username: alexkaskasoli

  # Build settings ...
sass:
  style: compressed
markdown: kramdown
highlighter: rouge
auto_ids: true
encoding: "utf-8"
paginate: 10
permalink: /post/:title
paginate_path: "/page/:num/"

  # Plugins ...
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
    # - jekyll-crosspost-to-medium
